<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SynerGy.RAG.Application\SynerGy.RAG.Application.csproj" />
    <ProjectReference Include="..\SynerGy.RAG.Domain\SynerGy.RAG.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Audit\" />
    <Folder Include="Configuration\" />
    <Folder Include="Security\" />
    <Folder Include="Rag\" />
    <Folder Include="Ollama\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.1.1" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.0" />
  </ItemGroup>

</Project>
